main:
  - name: Posts
    identifier: posts
    url: posts/
    weight: 1
  - name: Tags
    identifier: tags
    url: tags/
    weight: 2
  - name: About me
    identifier: about
    url: about/
    weight: 100
