main:
  - name: Posty
    identifier: posts
    url: posts/
    weight: 1
  - name: Tagi
    identifier: tags
    url: tags/
    weight: 2
  - name: O mnie
    identifier: about
    url: about/
    weight: 100
